name: Node CI

on: 
  pull_request:

permissions:
  contents: write
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 12.x
      - uses: actions/cache@v4
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}          
      - run: yarn install
      - run: yarn build-mat
      - name: tar files material-ui v4
        run: tar -cvf dist_v4.tar dist_v4
      - name: tar files material-ui v5
        run: tar -cvf dist_v5.tar dist_v5
      - name: Add artifact to github
        uses: actions/upload-artifact@v4
        with:
          name: material-ui-v4
          path: dist_v4.tar
      - name: Add artifact to github
        uses: actions/upload-artifact@v4
        with:
          name: material-ui-v5
          path: dist_v5.tar
  npm-publish-material-v4:
    needs: [build]
    name: npm-publish v4
    runs-on: ubuntu-latest
    # only on master
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 12.x
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: material-ui-v4
      - name: untar files
        run: tar -xvf dist_v4.tar
      - name: Publish if version in package.json change
        uses: springtype-org/github-action-npm-publish@master
        with:
          install_build_packages: true
          project_build_dir: dist_v4
          create_tag: true
          auth_token: ${{ secrets.npm_token }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  npm-publish-material-v5:
    needs: [build]
    name: npm-publish v5
    runs-on: ubuntu-latest
    # only on master
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 12.x
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: material-ui-v5
      - name: untar files
        run: tar -xvf dist_v5.tar
      - name: Publish if version in package.json change
        uses: springtype-org/github-action-npm-publish@master
        with:
          install_build_packages: true
          project_build_dir: dist_v5
          create_tag: true
          auth_token: ${{ secrets.npm_token }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  gh-pages:
    needs: [ build ]
    name: gh-pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 12.x
      - uses: actions/cache@v4
        with:
          path: 'demo/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('demo/yarn.lock') }}
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: material-ui-v4
      - name: untar files
        run: tar -xvf dist_v4.tar
      - name: build demo project
        working-directory: ./demo
        run: |
          yarn install
          yarn build
      - name: rename folder
        run: |
          cp demo/build/index.html demo/build/404.html
          mv demo/build docs
          tree -I 'node_modules|demo'      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs