name: Node CI

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 23 * * 0'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
      - run: yarn build-mat
      - name: tar files
        run: tar -cvf dist.tar dist
      - name: Add artifact to github
        uses: actions/upload-artifact@v2
        with:
          name: material-ui
          path: dist.tar
  npm-publish:
    needs: [build]
    name: npm-publish
    runs-on: ubuntu-latest
    # only on master
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: material-ui
      - name: untar files
        run: tar -xvf dist.tar
      - name: Publish if version in package.json change
        uses: springtype-org/github-action-npm-publish@master
        with:
          install_build_packages: true
          project_build_dir: dist
          create_tag: true
          auth_token: ${{ secrets.npm_token }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  gh-pages:
    needs: [ build ]
    name: gh-pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: material-ui
      - name: untar files
        run: tar -xvf dist.tar
      - name: move to demo project
        run: cd demo
      - name: show directory
        run: ls -lisha
      - name: install dependencies
        run: yarn install
      - name: build project
        run: yarn build
      - name: rename folder
        run: mv build docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # default: public