name: Node CI

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 23 * * 0'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}          
      - run: yarn install
      - run: yarn build-mat
      - name: tar files
        run: tar -cvf dist.tar dist
      - name: Add artifact to github
        uses: actions/upload-artifact@v2
        with:
          name: material-ui
          path: dist.tar
  npm-publish:
    needs: [build]
    name: npm-publish
    runs-on: ubuntu-latest
    # only on master
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: material-ui
      - name: untar files
        run: tar -xvf dist.tar
      - name: Publish if version in package.json change
        uses: springtype-org/github-action-npm-publish@master
        with:
          install_build_packages: true
          project_build_dir: dist
          create_tag: true
          auth_token: ${{ secrets.npm_token }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  gh-pages:
    needs: [ build ]
    name: gh-pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        with:
          path: 'demo/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('demo/yarn.lock') }}
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: material-ui
      - name: untar files
        run: tar -xvf dist.tar
      - name: update node_modules manually
        working-directory: ./demo
        run: |
          rm -rf node_modules/@material-ui-extra
          mkdir node_modules/@material-ui-extra
          cp -arv ../dist/*  node_modules/@material-ui-extra        
      - name: build demo project
        working-directory: ./demo
        run: |
          yarn install
          yarn build
      - name: rename folder
        run: |
          cp demo/build/index.html demo/build/404.html
          mv demo/build docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # default: public
